
var global_printer=null;function printmygridGO(obj){global_printer.printGrid(obj);}
function printmygridGOcustom(obj){global_printer.printCustom(obj);}
Ext.onReady(function(){Ext.QuickTips.init();var weekStore=new Ext.data.JsonStore({id:'weekStore',url:'data.php',root:'data',baseParams:{xtable:'week',task:'weekDropDown'},fields:[{name:'week'},{name:'date'}]});weekStore.load;var companyStore=new Ext.data.JsonStore({id:'companyStore',url:'data.php',root:'results',baseParams:{xtable:'company',task:'getCompany'},fields:[{name:'company_id',type:'int'},{name:'company_name'}]});var hourRecord=Ext.data.Record.create([{name:'hour_id',mapping:'hour_id'},{name:'company_name',mapping:'company_name'},{name:'user_firstname',mapping:'user_firstname'},{name:'user_lastname',mapping:'user_lastname'},{name:'regular_hours',mapping:'regular_hours'},{name:'user_regularpay',mapping:'user_regularpay'},{name:'regular_pay',mapping:'regular_pay'},{name:'otb_hours',mapping:'otb_hours'},{name:'user_otbpay',mapping:'user_otbpay'},{name:'otb_pay',mapping:'otb_pay'},{name:'total_due',mapping:'total_due'}]);var hourReader=new Ext.data.JsonReader({root:'results',totalProperty:'total',id:'hour_id'},hourRecord);hourDS=new Ext.data.GroupingStore({id:'hourDS',proxy:new Ext.data.HttpProxy({url:'data.php',method:'POST'}),baseParams:{start:0,limit:10000,task:'payrollReport',xtable:'hour'},reader:hourReader,sortInfo:{field:'hour_id',direction:'ASC'},groupField:'company_name'});Ext.ux.grid.GroupSummary.Calculations['totalCost']=function(v,record,field){return v+(record.data.hour_num*record.data.user_regularpay);};var summary=new Ext.ux.grid.GroupSummary();var companyRecord=Ext.data.Record.create([{name:'company_id',mapping:'company_id'},{name:'company_name',mapping:'company_name'}]);var companyReader=new Ext.data.JsonReader({root:'data',totalProperty:'total',id:'company_id'},companyRecord);companyDS=new Ext.data.GroupingStore({id:'companyDS',proxy:new Ext.data.HttpProxy({url:'grid-reconfigure.php',method:'POST'}),baseParams:{task:'readCompany',xtable:'company'},reader:companyReader,sortInfo:{field:'company_id',direction:'ASC'}});function handleDelete(){var selectedKeys=grid.selModel.selections.keys;if(selectedKeys.length>0)
{Ext.MessageBox.confirm('Message','Do you really want to delete this company?',deleteRecord);}
else
{Ext.MessageBox.alert('Message','Please select a company to delete');}};function refreshGrid(){hourDS.reload();}
function updateDB(oGrid_Event){if(oGrid_Event.value instanceof Date)
{var fieldValue=oGrid_Event.value.format('Y-m-d H:i:s');}else
{var fieldValue=oGrid_Event.value;}
Ext.Ajax.request({waitMsg:'Saving changes...',url:'grid-reconfigure.php',params:{task:"update",key:company_id,xtable:'company',keyID:oGrid_Event.record.data.company_id,field:oGrid_Event.field,value:fieldValue,originalValue:oGrid_Event.record.modified},failure:function(response,options){Ext.MessageBox.alert('Warning','Oops...');},success:function(response,options){if(oGrid_Event.record.data.company_id==''){var responseData=Ext.util.JSON.decode(response.responseText);var newID=responseData.newID;oGrid_Event.record.set('newRecord','no');oGrid_Event.record.set('company_id',newID);ds.commitChanges();}else{ds.commitChanges();}}});};function handleEdit(editEvent){var gridField=editEvent.field;updateDB(editEvent);if(gridField=='price'){getTax(editEvent);}}
function addRecord(){var r=new companyRecord({company_id:'',company_name:''});hourGrid.stopEditing();companyDS.insert(0,r);hourGrid.startEditing(0,1);};function handleDateRange(start,end){d1=start.format('Y-m-d');if(end){d2=end.format('Y-m-d');}else{d2=d1;}
hourDS.baseParams.startdate=d1;hourDS.baseParams.enddate=d2;hourDS.load({params:{start:0,limit:90}});}
var myMaxDate=Date.parse('today+10years');var weekDropDown=new Ext.form.ComboBox({id:'weekDropDown',triggerAction:'all',store:weekStore,displayField:'week',valueField:'date',labelSeparator:null,fieldLabel:'Week:',listClass:'x-combo-list-small',allowBlank:false});var dateForm1=new Ext.FormPanel({labelWidth:80,frame:true,border:false,baseCls:'x-toolbar',bodyStyle:'padding:3px',items:[weekDropDown]});var dateForm=new Ext.FormPanel({labelWidth:80,frame:true,border:false,baseCls:'x-toolbar',bodyStyle:'padding:3px',items:[new Ext.ux.form.DateRange({maxDate:myMaxDate,fieldLabel:'Date Range',handler:handleDateRange})]});var companyname_edit=new Ext.form.TextField();var money=function(val){return Ext.util.Format.number(val,'$?0,000.00?');}
var hourColumnModel=new Ext.grid.ColumnModel([{header:"ID",width:20,dataIndex:'company_id',sortable:true,hidden:true},{header:"Company",width:190,dataIndex:'company_name',sortable:true,hidden:false},{header:"Employee First Name",width:190,dataIndex:'user_firstname',editor:companyname_edit,sortable:true,hidden:false},{header:"Employee Last Name",width:190,dataIndex:'user_lastname',editor:companyname_edit,sortable:true,hidden:false},{header:"Regular Hours",width:190,align:'right',dataIndex:'regular_hours',sortable:true,hidden:false},{header:"Regular Rate",width:190,align:'right',dataIndex:'user_regularpay',sortable:true,hidden:false,type:'float',renderer:money},{header:"Regular Pay",width:190,align:'right',dataIndex:'regular_pay',sortable:true,hidden:false,type:'float',renderer:money},{header:"OTB Hours",width:190,align:'right',dataIndex:'otb_hours',sortable:true,hidden:false,type:'int',renderer:money},{header:"OTB Rate",width:190,align:'right',dataIndex:'user_otbpay',sortable:true,hidden:false,type:'float',renderer:money},{header:"OTB Pay",width:190,align:'right',dataIndex:'otb_pay',sortable:true,hidden:false,type:'float',renderer:money},{header:"Total Due",width:190,align:'right',dataIndex:'total_due',sortable:true,hidden:false,renderer:money}]);var datePicker=new Ext.menu.DateMenu({usePickerPlus:true,noOfMonth:1,markWeekends:true,multiSelection:true,markNationalHolidays:true,useQuickTips:false,strictRangeSelect:true,renderTodayButton:true,showToday:false,handler:function(dp,date){var allStringDates=[];var dateParam='';if(Ext.isDate(date)){allStringDates.push(date.format('Y-m-d'));}
else{Ext.each(date,function(c){allStringDates.push(c.format('Y-m-d'));},this);}
for(var i=0;i<allStringDates.length;i++){if(i==0){dateParam=allStringDates[i];}else{dateParam=dateParam+','+allStringDates[i];}}
hourDS.baseParams.dateParam=dateParam;hourDS.load({params:{start:0,limit:90}});}});var hourGrid=new Ext.grid.EditorGridPanel({iconCls:'clock',loadMask:true,stripeRows:true,cellclick:function()
{var record=hourGrid.getStore().getAt(rowIndex);var fieldName=hourGrid.getColumnModel().getDataIndex(columnIndex);var data=record.get(fieldName);Ext.MessageBox.alert('title','inside function');},autoWidth:true,clickstoEdit:1,sm:new Ext.grid.RowSelectionModel({singleSelect:true}),autoHeight:true,store:hourDS,cm:hourColumnModel,border:false,autoExpandColumn:'Name',trackMouseOver:true,tbar:[{text:'Date Range',iconCls:'calendar',tooltip:{title:'Dates for Payroll Report',text:''},menu:datePicker},'-',{text:'Add Timesheet',tooltip:'Click to Add a row',iconCls:'add',handler:addRecord},'-',{text:'Delete Selected',tooltip:'Click to Delete selected row(s)',handler:handleDelete,iconCls:'del'},'-',{text:'Refresh',tooltip:'Click to Refresh the table',handler:refreshGrid,iconCls:'reload'},'-',{xtype:'button',text:'Print',id:'downloadpdf',tooltip:'Print Projects Report',icon:'images/icons/printer.png',enableKeyEvents:true,handler:basic_printGrid}],view:new Ext.grid.GroupingView({forceFit:true,showGroupname:false,enableNoGroups:false,groupTextTpl:'{text} ({[values.rs.length]} {[values.rs.length > 1 ? "Items" : "Item"]})'}),plugins:summary});hourGrid.addListener('afteredit',handleEdit);var viewport=new Ext.Viewport({stateId:'viewport-stateid',stateful:true,layout:'border',defaults:{collapsible:false,split:true},items:[{region:'center',id:'centerpanel',autoScroll:true,frame:false,containerScroll:false,border:true,items:[hourGrid]}]});function basic_printGrid(){global_printer=new Ext.grid.XPrinter({grid:hourGrid,pathPrinter:'./printer',pdfEnable:true,hasrowAction:false,localeData:{Title:'Wall Systems Supply',subTitle:'Payroll and Scheduling Systems - Payroll Report',footerText:'&copy 2010 - Wall Systems Supply, Priviledged and Confidential Information',pageNo:'Page # ',printText:'Print',closeText:'Close',pdfText:'PDF'},useCustom:{custom:false,customStore:null,columns:[],alignCols:[],pageToolbar:null,useIt:false,showIt:false,location:'bbar'},showdate:true,showdateFormat:'Y-F-d H:i:s',showFooter:true,styles:'default'});global_printer.prepare();};});Ext.onPrinting(function(){Ext.addStyleSheet("printer-friendly-array-grid.css");Ext.state.Manager.setProvider(new Ext.state.CookieProvider());new Ext.Panel({renderTo:"body",layout:"table",layoutConfig:{columns:1},border:false,bodyBorder:false,items:[new Ext.BoxComponent({el:'description'}),new Ext.ux.grid.PrinterGridPanel({store:hourDS,columns:hourColumnModel,stateId:'array-grid',title:'Array Grid'})]});});